spring:
  datasource:
    driver-class-name: org.h2.Driver
    url:
    username:
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

logging.level:
  org.hibernate.SQL: info

