server:
  port: 7878

spring:
  config:
    additional-location: classpath:/prop.env
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url:
    username:
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true

logging.level:
  org.hibernate.SQL: debug

