server:
  port: 7878

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/ddh;DB_CLOSE_DELAY=-1
    username: nimkoes
    password: 180194
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true

logging.level:
  org.hibernate.SQL: debug

